version: '3'
services:
  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - "27017:27017"

  app:
    image: patientregistry
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/patientRegistryUpdated
      MONGO_DB: patientRegistryUpdated